<a href="https://colab.research.google.com/github/NaliniAparna/AI-Smart-Warehouse-Management/blob/main/notebooks/01_Data_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

project_path = "/content/drive/MyDrive/Projects/AI_Smart_Warehouse_Management/01_Raw Data"

os.listdir(project_path)

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'olist_orders_dataset.csv',
 'product_category_name_translation.csv']

In [5]:
import pandas as pd

In [6]:
# Step 1: Load the datasets
orders = pd.read_csv(
    os.path.join(project_path, "olist_orders_dataset.csv")
)

order_items = pd.read_csv(
    os.path.join(project_path, "olist_order_items_dataset.csv")
)

products = pd.read_csv(
    os.path.join(project_path, "olist_products_dataset.csv")
)

In [7]:
# Step 2 — Check their size
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)

Orders: (99441, 8)
Order Items: (112650, 7)
Products: (32951, 9)

In [9]:
# Step 3 - Columns in  table
print("ORDERS COLUMNS:")
print(orders.columns.tolist())

print("\nORDER ITEMS COLUMNS:")
print(order_items.columns.tolist())

print("\nPRODUCT COLUMNS:")
print(products.columns.tolist())

ORDERS COLUMNS:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

ORDER ITEMS COLUMNS:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

PRODUCT COLUMNS:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [10]:
print("Number of unique orders:", orders["order_id"].nunique())

print("Number of order-item rows:", len(order_items))

print("Number of unique products:", products["product_id"].nunique())

Number of unique orders: 99441
Number of order-item rows: 112650
Number of unique products: 32951

In [12]:
order_items["order_id"].value_counts().head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
af822dacd6f5cff7376413c03a388bb7    12
Name: count, dtype: int64

In [ ]:
# Each order ID can have multiple order iteams

In [ ]:
# ### Determine Historical Period
# Find the earliest and latest order dates to understand the time period available for demand forecasting.

<!-- ### Determine Historical Period
Find the earliest and latest order dates to understand the time period
available for demand forecasting. **bold text** -->

In [13]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

print("Start date:",
      orders["order_purchase_timestamp"].min())

print("End date:",
      orders["order_purchase_timestamp"].max())

Start date: 2016-09-04 21:15:19
End date: 2018-10-17 17:30:18

In [14]:
# ### Analyze Order Status
# Count orders by their current status to understand completed, canceled, unavailable, and other types of transactions.
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [15]:
# ### Load Supporting Olist Tables
# Load customer, seller, payment, review, geolocation, and product-category translation data to understand the complete e-commerce ecosystem.
customers = pd.read_csv(
    os.path.join(project_path, "olist_customers_dataset.csv")
)

sellers = pd.read_csv(
    os.path.join(project_path, "olist_sellers_dataset.csv")
)

payments = pd.read_csv(
    os.path.join(project_path, "olist_order_payments_dataset.csv")
)

reviews = pd.read_csv(
    os.path.join(project_path, "olist_order_reviews_dataset.csv")
)

geolocation = pd.read_csv(
    os.path.join(project_path, "olist_geolocation_dataset.csv")
)

category_translation = pd.read_csv(
    os.path.join(project_path, "product_category_name_translation.csv")
)

In [16]:
# ### Check Supporting Dataset Dimensions
# Check the size of the remaining tables to understand the volume of customer, seller, payment, review, location, and category data.
print("Customers:", customers.shape)
print("Sellers:", sellers.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Geolocation:", geolocation.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Sellers: (3095, 4)
Payments: (103886, 5)
Reviews: (99224, 7)
Geolocation: (1000163, 5)
Category Translation: (71, 2)

In [17]:
# ### Identify Supporting Table Columns
# Review the columns in each supporting table to understand what information is available and how the tables can be connected.
print("\nCUSTOMERS:")
print(customers.columns.tolist())

print("\nSELLERS:")
print(sellers.columns.tolist())

print("\nPAYMENTS:")
print(payments.columns.tolist())

print("\nREVIEWS:")
print(reviews.columns.tolist())

print("\nGEOLOCATION:")
print(geolocation.columns.tolist())

print("\nCATEGORY TRANSLATION:")
print(category_translation.columns.tolist())

CUSTOMERS:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

SELLERS:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

PAYMENTS:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

REVIEWS:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

GEOLOCATION:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

CATEGORY TRANSLATION:
['product_category_name', 'product_category_name_english']